name: nes_dart
description: NES emulator
version: 0.0.1
homepage: https://github.com/xiaohuihuiold/nes_dart
repository: https://github.com/xiaohuihuiold/nes_dart

environment:
  sdk: '>=3.1.0-117.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.3.0
  date_format: ^2.0.7
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
